/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_keplerproject_luajava_LuaStateFactory */

#ifndef _Included_org_keplerproject_luajava_LuaStateFactory
#define _Included_org_keplerproject_luajava_LuaStateFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_keplerproject_luajava_LuaStateFactory
 * Method:    getAkuState
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_keplerproject_luajava_LuaStateFactory_getAkuState
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
